---
notifications:
  email:
    on_success: never
    on_failure: change

cache: pip

sudo: true

language: python

matrix:
  include:
    - python: '2.7'
      env:
        TOXENV: 'py27'
        PIP_PACKAGE: 'python-pip'
        WHEEL: 'https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.1-cp27-cp27mu-linux_x86_64.whl'
    - python: '3.6'
      env:
        TOXENV: 'py36'
        PIP_PACKAGE: 'python3-pip'
        WHEEL: 'https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04/wxPython-4.0.1-cp36-cp36m-linux_x86_64.whl'

install:
  # - sudo apt-get install -y dpkg-dev build-essential python-dev libjpeg-dev libtiff5-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libgtk-3-dev libwebkitgtk-3.0-dev libgstreamer-plugins-base1.0-dev
  # - pip install tox-travis
  - pip install tox coveralls
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-14.04 wxPython
  - python setup.py install

script:
  - tox -vv

after_script:
  - coveralls
