---
notifications:
  email:
    on_success: never
    on_failure: change

sudo: true

language: python
python:
  - '2.7'
  - '3.6'

install:
  - sudo apt-get install -y dpkg-dev build-essential python2.7-dev python3.6-dev libjpeg-dev libtiff-dev libsdl1.2-dev libgstreamer-plugins-base0.10-dev libnotify-dev freeglut3 freeglut3-dev libsm-dev libgtk-3-dev libwebkitgtk-3.0-dev libgstreamer-plugins-base1.0-dev libwebkit2gtk-4.0-dev libsdl2-dev
  - pip install tox-travis coveralls
  - python setup.py install

script:
  - tox

after_script:
  - coveralls
